name: hson_dart
description: Hash checked JSON library for Dart implementation (HSON dynamic library file is not included in this package)
version: 1.1.2+1
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/hson_dart
issue_tracker: https://github.com/rk0cc/will_pub/issues
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  ffi: ">=1.1.2 <1.2.0"
  path: ^1.8.0
dev_dependencies:
  test: ^1.19.2