name: hson_dart
description: HSON Dart implementation
version: 1.0.0+1
homepage: https://www.rk0cc.xyz
repository: https://github.com/rk0cc/hson_dart
issue_tracker: https://github.com/rk0cc/will_pub/issues
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  ffi: ^1.1.2
dev_dependencies:
  test: ^1.19.1
  path: ^1.8.0