name: hson_dart
description: HSON Dart implementation
version: 1.0.0
homepage: https://www.rk0cc.xyz
repository: https://github.com/will_pub/hson_dart
issue_tracker: https://github.com/will_pub/issues
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  ffi: ^1.1.2
