name: Dart
on:
  push:
    branches:
      - main
    paths:
      - lib/**.dart
      - test/**.dart
      - pubspec.yaml
      - .github/workflows/dart.yml
jobs:
  build:
    name: HSON test
    runs-on: ubuntu-latest
    steps:
      - name: Run it at your MOTHERFUCKING COMPUTER
        run: ls -a