name: Dart
on:
  push:
    branches:
      - main
    paths:
      - lib/**.dart
      - test/**.dart
      - pubspec.yaml
      - .github/workflows/dart.yml
jobs:
  build:
    name: HSON test
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - stable
          - beta
          - dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
      - name: Get dependencies
        run: dart pub get
      - name: Download library
        uses: wei/wget@v1.1.1
        with:
          args: -O /home/runner/work/hson_dart/hson_dart/hson.zip https://github.com/rk0cc/hson/releases/download/1.0.0/hson_linux_amd64.zip
      - name: Setup unzip
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -q /home/runner/work/hson_dart/hson_dart/hson.zip
      - name: Do test
        run: dart test